### ISSUE TITLE
css

### ISSUE THREAD

**Issue by MengZhaoFly** [MengZhaoFly/blog#51]
## BFC
BFC 即 `Block Formatting Contexts (块级格式化上下文)`。

### 触发 BFC
只要元素满足下面任一条件即可触发 BFC 特性：

- body 根元素
- 浮动元素：float 除 none 以外的值
- 绝对定位元素：position (absolute、fixed)
- display 为 inline-block、table-cells、flex
- overflow 除了 visible 以外的值 (hidden、auto、scroll)

### BFC布局规则：
1. 内部的Box会在垂直方向，一个接一个地放置。
2. Box垂直方向的距离由margin决定。属于同一个BFC的两个相邻Box的margin会发生重叠
3. 每个元素的margin box的左边， 与包含块border box的左边相接触(对于从左往右的格式化，否则相反)。即使存在浮动也是如此。
4. BFC的区域不会与float box重叠。
5. BFC就是页面上的一个隔离的独立容器，容器里面的子元素不会影响到外面的元素。反之也如此。
6. 计算BFC的高度时，浮动元素也参与计算

### 规则

- 边距叠加
```html
<style>
  .box {
    width: 40px;
    height: 40px;
  }
  .box1 {
    background-color: black;
    margin-bottom: 100px;
  }
  .box2 {
    background-color: aqua;
    margin-top: 100px;
  }
  .bfc {
    overflow: hidden;
  }
  </style>
</head>
<body>
    <div class="box box1"></div>
    <div class="bfc">
      <div class="box box2"></div>
    </div>
</body>
```
- 清除内部浮动
```css
.container {
    border: 1px solid #000;
    overflow: hidden;
  }
```
- BFC 不会和 float 元素叠加
```css
<style>
    .aside {
      width: 100px;
      height: 150px;
      float: left;
      background: #f66;
    }

    .text {
      width: 500px;
      height: 200px;
      overflow: hidden;
      background: #fcc;
    }
  </style>
<div class="aside"></div>
  <div class="text">

  </div>
```
没有 BFC 之前
![image](https://user-images.githubusercontent.com/19408342/71321494-f76da680-24f4-11ea-8fb3-9b1277af7695.png)
创建 BFC
![image](https://user-images.githubusercontent.com/19408342/71321504-153b0b80-24f5-11ea-9524-59314021e8f8.png)
