### ISSUE TITLE
css 与 数学

### ISSUE THREAD

**Issue by MengZhaoFly** [MengZhaoFly/blog#52]
## 菱形绘制
- transform：
html:
```html
<div class="box">
        <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1577026869827&di=c354d710c63429eec8c21336084f4ea2&imgtype=jpg&src=http%3A%2F%2Fimg0.imgtn.bdimg.com%2Fit%2Fu%3D2605347270%2C1074964422%26fm%3D214%26gp%3D0.jpg" alt="">
    </div>
```
css:
```css
.box {
    height: 200px;
    width: 200px;
    margin: 50px;
    transform: rotate(45deg);
    background: yellowgreen;
    overflow: hidden;
}
.box img {
    height: 100%;
    transform: rotate(-45deg) scale(1.42);
}
```
最后一步计算缩放的倍数：

<img width="364" alt="QQ20191224-183725@2x" src="https://user-images.githubusercontent.com/19408342/71409429-82c57400-267c-11ea-8dc1-d9db1dba5bbc.png">

```css
    /* 要扩大的变长 / 200 = sin45 
    要扩大的变长 = 2 分支 根号 2 * 200 = 100 * 根号2
    比率：100 * Math.sqrt(2) / 100 = 1.42
    */
```

- clip-path：
polygon：指定需要绘制的几个点
```css
<style>
    img {
        height: 200px;
        width: 200px;
        margin: 50px;
        clip-path: polygon(50% 0, 100% 50%, 50% 100%, 0 50%);
    }
</style>
</head>
<body>
    <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1577026869827&di=c354d710c63429eec8c21336084f4ea2&imgtype=jpg&src=http%3A%2F%2Fimg0.imgtn.bdimg.com%2Fit%2Fu%3D2605347270%2C1074964422%26fm%3D214%26gp%3D0.jpg" alt="">
</body>
```
